# Netlify 프론트엔드 전용 설정
[build]
  publish = "build"
  command = "npm install && DISABLE_ESLINT_PLUGIN=true npm run build"

# 환경 변수
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"
  NODE_ENV = "production"

# SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
